export { Benefits } from "./benefits"
export { Footer } from "./footer"
export { Hero } from "./hero"
export { HowItWorks } from "./how-it-works"
export { Navbar } from "./navbar"
export { Pricing } from "./pricing"
export { TargetPersonas } from "./target-personas"
export { Testimonials } from "./testimonials"
