INSERT INTO directories (id, name, domain, submit_url, slug_pattern, category, check_method, is_free, is_active) VALUES

-- Launch Platforms
(gen_random_uuid(), 'Product Hunt', 'producthunt.com', 'https://www.producthunt.com/posts/new', 'https://www.producthunt.com/products/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'BetaList', 'betalist.com', 'https://betalist.com/submit', 'https://betalist.com/startups/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'Uneed', 'uneed.best', 'https://www.uneed.best/submit', 'https://www.uneed.best/tool/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'Microlaunch', 'microlaunch.net', 'https://microlaunch.net/submit', 'https://microlaunch.net/p/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'DevHunt', 'devhunt.org', 'https://devhunt.org/submit', 'https://devhunt.org/tool/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'Launching Next', 'launchingnext.com', 'https://www.launchingnext.com/submit/', 'https://www.launchingnext.com/startup/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'StartupStash', 'startupstash.com', 'https://startupstash.com/submit/', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Betapage', 'betapage.co', 'https://betapage.co/submit-startup', 'https://betapage.co/startup/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'Pitchwall', 'pitchwall.co', 'https://pitchwall.co/submit', 'https://pitchwall.co/product/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'Launched', 'launched.io', 'https://launched.io/submit', 'https://launched.io/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'Startup Buffer', 'startupbuffer.com', 'https://startupbuffer.com/site/submit', 'https://startupbuffer.com/startups/{slug}', 'launch', 'head_check', true, true),
(gen_random_uuid(), 'Fazier', 'fazier.com', 'https://fazier.com/submit', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'LaunchIgniter', 'launchigniter.com', 'https://launchigniter.com/submit', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'TinyLaunch', 'tinylaunch.com', 'https://tinylaunch.com/submit', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'OpenHunts', 'openhunts.com', 'https://openhunts.com/submit', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'SoloPush', 'solopush.com', 'https://solopush.com/submit', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Startup Fame', 'startupfa.me', 'https://startupfa.me/submit', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Startup Inspire', 'startupinspire.com', 'https://startupinspire.com/submit', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Tiny Startups', 'tinystartups.com', 'https://www.tinystartups.com/', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Startups Gallery', 'startups.gallery', 'https://startups.gallery/', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Startups FYI', 'startups.fyi', 'https://www.startups.fyi/', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Startup Spotlight', 'startupspotlight.co', 'https://www.startupspotlight.co/', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'BuiltIn24', 'builtin24.com', 'https://www.builtin24.com/', null, 'launch', 'serp_check', true, true),
(gen_random_uuid(), 'Post Your Startup', 'postyourstartup.co', 'https://postyourstartup.co/login', null, 'launch', 'serp_check', true, true),

-- Review & Comparison Sites
(gen_random_uuid(), 'G2', 'g2.com', 'https://sell.g2.com/free-listing', 'https://www.g2.com/sellers/{slug}', 'review', 'head_check', true, true),
(gen_random_uuid(), 'Capterra', 'capterra.com', 'https://vendors.capterra.com/listing/add', null, 'review', 'serp_check', true, true),
(gen_random_uuid(), 'GetApp', 'getapp.com', 'https://vendors.capterra.com/listing/add', null, 'review', 'serp_check', true, true),
(gen_random_uuid(), 'Software Advice', 'softwareadvice.com', 'https://vendors.capterra.com/listing/add', null, 'review', 'serp_check', true, true),
(gen_random_uuid(), 'Trustpilot', 'trustpilot.com', 'https://business.trustpilot.com/signup', 'https://www.trustpilot.com/review/{slug}', 'review', 'head_check', true, true),
(gen_random_uuid(), 'TrustRadius', 'trustradius.com', 'https://www.trustradius.com/vendor/sign-up', 'https://www.trustradius.com/products/{slug}', 'review', 'head_check', true, true),
(gen_random_uuid(), 'Crozdesk', 'crozdesk.com', 'https://crozdesk.com/add-software', 'https://crozdesk.com/software/{slug}', 'review', 'head_check', true, true),
(gen_random_uuid(), 'GoodFirms', 'goodfirms.co', 'https://www.goodfirms.co/software/list-your-software', 'https://www.goodfirms.co/software/{slug}', 'review', 'head_check', true, true),
(gen_random_uuid(), 'Clutch', 'clutch.co', 'https://clutch.co/get-listed', 'https://clutch.co/profile/{slug}', 'review', 'head_check', true, true),
(gen_random_uuid(), 'SoftwareWorld', 'softwareworld.co', 'https://www.softwareworld.co/list-your-product/', null, 'review', 'serp_check', false, true),
(gen_random_uuid(), 'SaaSworthy', 'saasworthy.com', 'https://www.saasworthy.com/', null, 'review', 'serp_check', true, true),
(gen_random_uuid(), 'Tekpon', 'tekpon.com', 'https://tekpon.com/get-listed/', null, 'review', 'serp_check', false, true),

-- General Software Directories
(gen_random_uuid(), 'AlternativeTo', 'alternativeto.net', 'https://alternativeto.net/add-app/', 'https://alternativeto.net/software/{slug}/', 'software', 'head_check', true, true),
(gen_random_uuid(), 'SaaSHub', 'saashub.com', 'https://www.saashub.com/add-software', 'https://www.saashub.com/{slug}', 'software', 'head_check', true, true),
(gen_random_uuid(), 'StackShare', 'stackshare.io', 'https://stackshare.io/new-tool', 'https://stackshare.io/{slug}', 'software', 'head_check', true, true),
(gen_random_uuid(), 'SourceForge', 'sourceforge.net', 'https://sourceforge.net/projects/add/', 'https://sourceforge.net/projects/{slug}/', 'software', 'head_check', true, true),
(gen_random_uuid(), 'Softpedia', 'softpedia.com', 'https://www.softpedia.com/get/submit-your-program', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'Open Source Alternatives To', 'opensourcealternative.to', 'https://opensourcealternative.to/submit', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'Active Search Results', 'activesearchresults.com', 'https://www.activesearchresults.com/addwebsite.php', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'Launch Directories', 'launchdirectories.com', 'https://launchdirectories.com/', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'Nx Gn Tools', 'nxgntools.com', 'https://www.nxgntools.com/', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'Dev Pages', 'devpages.io', 'https://www.devpages.io/submit', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'Alternative.me', 'alternative.me', 'https://alternative.me/', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'OpenAlternative', 'openalternative.co', 'https://openalternative.co/submit', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'EuroAlternative', 'euroalternative.eu', 'https://euroalternative.eu/submit', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'DevSuite', 'devsuite.co', 'https://devsuite.co/submit', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'NoCodeList', 'nocodelist.co', 'https://nocodelist.co/submit', null, 'software', 'serp_check', true, true),
(gen_random_uuid(), 'FiveTaco', 'fivetaco.com', 'https://fivetaco.com/', null, 'software', 'serp_check', true, true),

-- Startup & Company Directories
(gen_random_uuid(), 'Crunchbase', 'crunchbase.com', 'https://www.crunchbase.com/add-to-database', 'https://www.crunchbase.com/organization/{slug}', 'startup', 'head_check', true, true),
(gen_random_uuid(), 'Wellfound', 'wellfound.com', 'https://wellfound.com/company/new', 'https://wellfound.com/company/{slug}', 'startup', 'head_check', true, true),
(gen_random_uuid(), 'F6S', 'f6s.com', 'https://www.f6s.com/company/apply', 'https://www.f6s.com/company/{slug}', 'startup', 'head_check', true, true),
(gen_random_uuid(), 'Startup Ranking', 'startupranking.com', 'https://www.startupranking.com/add-startup', 'https://www.startupranking.com/{slug}', 'startup', 'head_check', true, true),
(gen_random_uuid(), 'Tech In Asia', 'techinasia.com', 'https://www.techinasia.com/contact', null, 'startup', 'serp_check', true, true),
(gen_random_uuid(), 'TechPluto', 'techpluto.com', 'https://www.techpluto.com/submit-a-startup/', null, 'startup', 'serp_check', true, true),
(gen_random_uuid(), 'Startup Beat', 'startupbeat.com', 'https://startupbeat.com/get-featured/', null, 'startup', 'serp_check', true, true),
(gen_random_uuid(), 'Startup Base', 'startupbase.io', 'https://startupbase.io/', null, 'startup', 'serp_check', true, true),
(gen_random_uuid(), 'The Startup INC', 'thestartupinc.com', 'https://www.thestartupinc.com/submit-startup/', null, 'startup', 'serp_check', false, true),
(gen_random_uuid(), 'IndieHustles', 'indiehustles.com', 'https://indiehustles.com/', null, 'startup', 'serp_check', true, true),

-- Community & Discussion
(gen_random_uuid(), 'Indie Hackers', 'indiehackers.com', 'https://www.indiehackers.com/post/new', 'https://www.indiehackers.com/product/{slug}', 'community', 'head_check', true, true),
(gen_random_uuid(), 'Peerlist', 'peerlist.io', 'https://peerlist.io/tools/submit', 'https://peerlist.io/tools/{slug}', 'community', 'head_check', true, true),
(gen_random_uuid(), 'SideProjectors', 'sideprojectors.com', 'https://www.sideprojectors.com/project/create', null, 'community', 'serp_check', true, true),
(gen_random_uuid(), 'PeerPush', 'peerpush.net', 'https://peerpush.net/', null, 'community', 'serp_check', true, true),
(gen_random_uuid(), 'Devpost', 'devpost.com', 'https://devpost.com/software/new', null, 'community', 'serp_check', true, true),
(gen_random_uuid(), 'WIP', 'wip.co', 'https://wip.co/', null, 'community', 'serp_check', true, true),
(gen_random_uuid(), 'Indie Hacker Stacks', 'indiehackerstacks.com', 'https://indiehackerstacks.com/', null, 'community', 'serp_check', true, true),

-- AI Directories
(gen_random_uuid(), 'Futurepedia', 'futurepedia.io', 'https://www.futurepedia.io/submit-tool', 'https://www.futurepedia.io/tool/{slug}', 'ai', 'head_check', true, true),
(gen_random_uuid(), 'There''s An AI For That', 'theresanaiforthat.com', 'https://theresanaiforthat.com/submit/', 'https://theresanaiforthat.com/ai/{slug}/', 'ai', 'head_check', true, true),
(gen_random_uuid(), 'Toolify', 'toolify.ai', 'https://www.toolify.ai/submit', 'https://www.toolify.ai/ai-tools/{slug}', 'ai', 'head_check', true, true),
(gen_random_uuid(), 'AI Top Tools', 'aitoptools.com', 'https://aitoptools.com/submit/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'Top AI Tools', 'topai.tools', 'https://topai.tools/submit', null, 'ai', 'serp_check', false, true),
(gen_random_uuid(), 'AI Tools Directory', 'aitoolsdirectory.com', 'https://aitoolsdirectory.com/submit-tool/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'Tool AI', 'toolai.io', 'https://toolai.io/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'Open Tools', 'opentools.ai', 'https://opentools.ai/submit-a-tool', null, 'ai', 'serp_check', false, true),
(gen_random_uuid(), 'AI Chief', 'aichief.com', 'https://aichief.com/submit-tool/', null, 'ai', 'serp_check', false, true),
(gen_random_uuid(), 'aitools.fyi', 'aitools.fyi', 'https://aitools.fyi/submit', null, 'ai', 'serp_check', false, true),
(gen_random_uuid(), 'ToolScout', 'toolscout.ai', 'https://toolscout.ai/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'Dokey AI', 'dokeyai.com', 'https://dokeyai.com/submit', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'AI Tool Trek', 'aitooltrek.com', 'https://aitooltrek.com/submit', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'BasedTools', 'basedtools.ai', 'https://www.basedtools.ai/submit-product', null, 'ai', 'serp_check', false, true),
(gen_random_uuid(), 'Toolio AI', 'toolio.ai', 'https://www.toolio.ai/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'AI Search', 'ai-search.io', 'https://ai-search.io/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'SaaSBaba', 'saasbaba.com', 'https://saasbaba.com/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'DigitalSamaritan', 'digitalsamaritan.co', 'https://www.digitalsamaritan.co/submit-a-tool', null, 'ai', 'serp_check', false, true),
(gen_random_uuid(), 'AI Hunter', 'ai-hunter.io', 'https://ai-hunter.io/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'ToolList.ai', 'toollist.ai', 'https://toollist.ai/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'AI Tools Guide', 'aitoolsguide.com', 'https://aitoolsguide.com/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'AI Zones', 'aizones.io', 'https://aizones.io/', null, 'ai', 'serp_check', false, true),
(gen_random_uuid(), 'Best AI Tools', 'startupaitools.com', 'https://www.startupaitools.com/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'AI Directory', 'aidirectory.org', 'https://www.aidirectory.org/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'BroUseAI', 'brouseai.com', 'https://www.brouseai.com/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'Future Tools', 'futuretools.io', 'https://www.futuretools.io/submit-a-tool', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'SaaS AI Tools', 'saasaitools.com', 'https://saasaitools.com/', null, 'ai', 'serp_check', true, true),
(gen_random_uuid(), 'AI Directories', 'aidirectori.es', 'https://www.aidirectori.es/pricing', null, 'ai', 'serp_check', false, true),

-- Marketplace
(gen_random_uuid(), 'AppSumo', 'appsumo.com', 'https://partners.appsumo.com', 'https://appsumo.com/products/{slug}/', 'marketplace', 'head_check', false, true)

ON CONFLICT DO NOTHING;
